### PR TITLE
fix RAINCATCH-130

### PR DESCRIPTION
**Pull request by leathersole**
Add procedure to set the auth policy name as WFM_AUTH_POLICY_ID environemental variable of the cloud app

### CODE REVIEW

**Comment by nialldonnellyfh** [comment]
@leathersole Thanks a lot. Looks good to me.

@sebastienblanc Want to take a quick look?

**Comment by sebastienblanc** [comment]
@leathersole Why is this step needed ? what is the difference with the step 7 where we set 'WFM_AUTH_GUID` ?

**Comment by leathersole** [comment]
I inserted the step 8 because the topic of step 7 is not related to the auth policy name and the size is just about the other steps.
@sebastienblanc do you think it's better to merge these steps? I don't mind that.

**Comment by sebastienblanc** [comment]
Ok, I get it now, this is only needed when the auth policy is not named `wfm` maybe we should state that this step is only needed if the policy is not called `wfm` ?

**Comment by leathersole** [comment]
@sebastienblanc , right. WFM_AUTH_POLICY_ID is not needed if the policy name is wfm. However, I feel it's better to add it even if the name is wfm. Because:
- The relation is fragile, since the policy name can change. 
- Other name based relations are clearer. e.g. Project Theme can be selected from a drop-down menu (Step 3).
- IMHO, the name "wfm" is too common. Customers may set other name like my_wfm, wfm_demo, wfm_test and so on, especially during evaluation or test phases.

**Pull request merged**
