### PR TITLE
Changes made after following the steps.

### PR DESCRIPTION
**Pull request by camilamacedo86**
- 	Replace Base Theme for Red Hat Theme 
-      	Corrections in the steps of the item: 4 - Create a new MBaaS Service…
-      	Add step 10 - Check the web app deploment in RHMAP

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Please, could someone review this pull request and approve it ?

**Comment by camilamacedo86** [comment]
@nialldonnellyfh  Could you check this PR ?

**Comment by nialldonnellyfh** [comment]
@camilamacedo86 This repo is no longer used. Can you move this PR to https://github.com/feedhenry-raincatcher/raincatcher-documentation

**Comment by camilamacedo86** [comment]
@nialldonnellyfh Thank you I will do it. :-)

**Pull request closed without merging**
